CREATE DATABASE ShopQuanAo
USE ShopQuanAo

-- Bảng khách hàng
CREATE TABLE KHACHHANG (
	MaKH CHAR(15) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50),
	GioiTinh NVARCHAR(10),
	NgaySinh CHAR(10),
	DiaChi NVARCHAR(20),
	SDT CHAR(15)
)

-- Bảng quản lý
CREATE TABLE QUANLY (
	MaQL CHAR(15) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50),
	GioiTinh NVARCHAR(10),
	NgaySinh CHAR(10),
	DiaChi NVARCHAR(20),
	SDT CHAR(15)
)
INSERT INTO QUANLY VALUES ('QL001', N'Nguyễn Văn Hải', N'Nam', '02/08/2003', N'Hải Dương', '0333301536')

-- Bảng sản phẩm
CREATE TABLE SANPHAM (
	MaSP CHAR(15) NOT NULL PRIMARY KEY,
	TenSP NVARCHAR(50),
	GiaSP FLOAT,
	NgayThem CHAR(25),
	GiamGia INT,
	urlImg CHAR(100) 
)

-- Bảng giỏ hàng
CREATE TABLE GIOHANG (
	MaKH CHAR(15) NOT NULL FOREIGN KEY REFERENCES KHACHHANG(MaKH), 
	MaSP CHAR(15) NOT NULL FOREIGN KEY REFERENCES SANPHAM(MaSP),
	PRIMARY KEY(MaKH, MaSP)
)

-- Bảng Tài khoản đăng nhập của khách hàng
CREATE TABLE TaiKhoanDangNhap (
	TenTK NVARCHAR(20) NOT NULL PRIMARY KEY,
	MatKhau NVARCHAR(20),
	Email CHAR(50),
	MaKH CHAR(15) FOREIGN KEY REFERENCES KHACHHANG(MaKH)
)

-- Bảng hóa đơn mua hàng
CREATE TABLE HOADON(
	MaKH CHAR(15) NOT NULL FOREIGN KEY REFERENCES KHACHHANG(MaKH), 
	MaSP CHAR(15) NOT NULL FOREIGN KEY REFERENCES SANPHAM(MaSP),
	NgayMua DATE,
	SoLuong INT,
	PRIMARY KEY(MaKH, MaSP)
)

-- Bảng quản lý sản phẩm
CREATE TABLE QuanLySanPham (
	MaQL CHAR(15) NOT NULL FOREIGN KEY REFERENCES QUANLY(MaQL),
	MaSP CHAR(15) NOT NULL FOREIGN KEY REFERENCES SANPHAM(MaSP),
	PRIMARY KEY(MaQL, MaSP)
)

-- Bảng quản lý khách hàng
CREATE TABLE QuanLyKhachHang (
	MaQL CHAR(15) NOT NULL FOREIGN KEY REFERENCES QUANLY(MaQL),
	MaKH CHAR(15) NOT NULL FOREIGN KEY REFERENCES KHACHHANG(MaKH),
	PRIMARY KEY(MaKH, MaQL)
)

-- Bảng quản lý tài khoản đăng nhập
CREATE TABLE QuanLyTaiKhoan (
	MaQL CHAR(15) NOT NULL FOREIGN KEY REFERENCES QUANLY(MaQL),
	TenTK NVARCHAR(20) NOT NULL FOREIGN KEY REFERENCES TaiKhoanDangNhap(TenTK),
	PRIMARY KEY(MaQL, TenTK)
)

-- Câu truy vấn
SELECT * FROM HOADON WHERE NgayMua BETWEEN '20220401' AND '20230403'

SELECT * FROM SANPHAM, GIOHANG WHERE SANPHAM.MaSP = GIOHANG.MaSP

SELECT * FROM GIOHANG WHERE MaKH = 47

SELECT G.MaSP TenSP, urlImg, GiaSP FROM SANPHAM AS S, GIOHANG AS G, KHACHHANG AS K 
WHERE S.MaSP = G.MaSP AND G.MaKH = K.MaKH AND K.MaKH = '47'	

SELECT * FROM KHACHHANG
SELECT * FROM TaiKhoanDangNhap
SELECT * FROM GIOHANG

Select TenTK, MatKhau from TaiKhoanDangNhap

SELECT K.MaKH FROM TaiKhoanDangNhap AS T, KHACHHANG AS K WHERE T.MaKH = K.MaKH 
AND K.MaKH IN (SELECT MaKH FROM TaiKhoanDangNhap WHERE TenTK = N'NguyenHai')

-- Lấy ra những sản phẩm bán được số lượng >= 5
SELECT H.MaSP, S.TenSP, S.GiaSP, S.DonViTinh , SUM(SoLuong) AS SOLUONG FROM SANPHAM AS S, HOADON AS H
WHERE S.MaSP = H.MaSP GROUP BY H.MaSP, S.TenSP, S.GiaSP, S.DonViTinh HAVING SUM(SoLuong) >= 5

-- Xóa
DROP TABLE QuanLyTaiKhoan
DROP TABLE QuanLyKhachHang
DROP TABLE QuanLySanPham
DROP TABLE HOADON
DROP TABLE TaiKhoanDangNhap
DROP TABLE GIOHANG
DROP TABLE SANPHAM
DROP TABLE QUANLY
DROP TABLE KHACHHANG