CREATE DATABASE ShopQuanAo
USE ShopQuanAo

CREATE TABLE KHACHHANG (
	MaKH CHAR(15) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50),
	GioiTinh NVARCHAR(10),
	NgaySinh CHAR(10),
	DiaChi NVARCHAR(20),
	SDT CHAR(15),
	LoaiKH NVARCHAR(10),
	SoTien FLOAT
)

CREATE TABLE QUANLY (
	MaQL CHAR(15) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50),
	GioiTinh NVARCHAR(10),
	NgaySinh CHAR(10),
	DiaChi CHAR(20), 
	SDT CHAR(15)
)

CREATE TABLE SANPHAM (
	MaSP CHAR(15) NOT NULL PRIMARY KEY,
	TenSP NVARCHAR(50),
	GiaSP FLOAT,
	DonViTinh NVARCHAR(20)
)

-- Thêm mới table giỏ hàng
CREATE TABLE GIOHANG (
	MaKH CHAR(15) NOT NULL FOREIGN KEY REFERENCES KHACHHANG(MaKH), 
	MaSP CHAR(15) NOT NULL FOREIGN KEY REFERENCES SANPHAM(MaSP),
	PRIMARY KEY(MaKH, MaSP)
)

CREATE TABLE TaiKhoanDangNhap (
	TenTK NVARCHAR(20) NOT NULL PRIMARY KEY,
	MatKhau NVARCHAR(20),
	Email CHAR(50),
	MaKH CHAR(15) FOREIGN KEY REFERENCES KHACHHANG(MaKH)
)

CREATE TABLE HOADON(
	MaKH CHAR(15) NOT NULL FOREIGN KEY REFERENCES KHACHHANG(MaKH), 
	MaSP CHAR(15) NOT NULL FOREIGN KEY REFERENCES SANPHAM(MaSP),
	NgayMua CHAR(10),
	SoLuong INT,
	PRIMARY KEY(MaKH, MaSP)
)

CREATE TABLE QuanLySanPham (
	MaQL CHAR(15) NOT NULL FOREIGN KEY REFERENCES QUANLY(MaQL),
	MaSP CHAR(15) NOT NULL FOREIGN KEY REFERENCES SANPHAM(MaSP),
	PRIMARY KEY(MaQL, MaSP)
)

CREATE TABLE QuanLyKhachHang (
	MaQL CHAR(15) NOT NULL FOREIGN KEY REFERENCES QUANLY(MaQL),
	MaKH CHAR(15) NOT NULL FOREIGN KEY REFERENCES KHACHHANG(MaKH),
	PRIMARY KEY(MaKH, MaQL)
)

CREATE TABLE QuanLyTaiKhoan (
	MaQL CHAR(15) NOT NULL FOREIGN KEY REFERENCES QUANLY(MaQL),
	TenTK NVARCHAR(20) NOT NULL FOREIGN KEY REFERENCES TaiKhoanDangNhap(TenTK),
	PRIMARY KEY(MaQL, TenTK)
)

SELECT * FROM HOADON WHERE NgayMua BETWEEN '20220401' AND '20230403'

SELECT * FROM SANPHAM
INSERT INTO SANPHAM VALUES ('SP001', N'Áo Khoác Nam', 20, N'Chiếc')
INSERT INTO SANPHAM VALUES ('SP002', N'Áo Len KaKi', 50, N'Chiếc')
INSERT INTO SANPHAM VALUES ('SP003', N'Áo Da Nam', 50, N'Chiếc')
INSERT INTO SANPHAM VALUES ('SP004', N'Quần Âu Nam', 34, N'Chiếc')
INSERT INTO SANPHAM VALUES ('SP005', N'Áo Sơ Mi', 99, N'Chiếc')
INSERT INTO SANPHAM VALUES ('SP006', N'Quần Bò Nam', 105, N'Chiếc')

SELECT * FROM SANPHAM, GIOHANG WHERE SANPHAM.MaSP = GIOHANG.MaSP

SELECT * FROM GIOHANG
SELECT * FROM KHACHHANG
SELECT * FROM TaiKhoanDangNhap


SELECT KHACHHANG.MaKH FROM TaiKhoanDangNhap, KHACHHANG WHERE TaiKhoanDangNhap.MaKH = KHACHHANG.MaKH 
AND KHACHHANG.MaKH IN (SELECT MaKH FROM TaiKhoanDangNhap WHERE TenTK = N'NguyenVanHai')


-- Xóa
DROP TABLE QuanLyTaiKhoan
DROP TABLE QuanLyKhachHang
DROP TABLE QuanLySanPham
DROP TABLE HOADON
DROP TABLE TaiKhoanDangNhap
DROP TABLE SANPHAM
DROP TABLE QUANLY
DROP TABLE KHACHHANG