//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_BHQA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI_BHQA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap _65844ee13d802b538236c05df5c0aa23 {
            get {
                object obj = ResourceManager.GetObject("65844ee13d802b538236c05df5c0aa23", resourceCulture);
=======
<<<<<<< HEAD
        internal static System.Drawing.Bitmap ao_khoac_nam_han_quoc_dep {
            get {
                object obj = ResourceManager.GetObject("ao-khoac-nam-han-quoc-dep", resourceCulture);
=======
        internal static System.Drawing.Bitmap _0af3c9613761d2d2394d99312aeba397 {
            get {
                object obj = ResourceManager.GetObject("0af3c9613761d2d2394d99312aeba397", resourceCulture);
>>>>>>> ed618cc62e6c9975de8b474ef372e0f1f3ad2b4e
>>>>>>> main
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap size_ao_khoac_nam_1 {
            get {
                object obj = ResourceManager.GetObject("size-ao-khoac-nam-1", resourceCulture);
=======
<<<<<<< HEAD
        internal static System.Drawing.Bitmap gif01 {
            get {
                object obj = ResourceManager.GetObject("gif01", resourceCulture);
=======
        internal static System.Drawing.Bitmap background_mau_xanh_009_1 {
            get {
                object obj = ResourceManager.GetObject("background-mau-xanh-009-1", resourceCulture);
>>>>>>> ed618cc62e6c9975de8b474ef372e0f1f3ad2b4e
>>>>>>> main
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap th {
            get {
                object obj = ResourceManager.GetObject("th", resourceCulture);
=======
<<<<<<< HEAD
        internal static System.Drawing.Bitmap giphy {
            get {
                object obj = ResourceManager.GetObject("giphy", resourceCulture);
=======
        internal static System.Drawing.Bitmap dangnhap_icon {
            get {
                object obj = ResourceManager.GetObject("dangnhap.icon", resourceCulture);
>>>>>>> ed618cc62e6c9975de8b474ef372e0f1f3ad2b4e
>>>>>>> main
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap z4231793101731_a09cb6f2e6b90438d1a2ec6d6891497b {
            get {
                object obj = ResourceManager.GetObject("z4231793101731_a09cb6f2e6b90438d1a2ec6d6891497b", resourceCulture);
=======
<<<<<<< HEAD
        internal static System.Drawing.Bitmap th__1_ {
            get {
                object obj = ResourceManager.GetObject("th (1)", resourceCulture);
=======
        internal static System.Drawing.Bitmap Graphics_Vibe_Hot_Burning_Social_Google_48__1_ {
            get {
                object obj = ResourceManager.GetObject("Graphics-Vibe-Hot-Burning-Social-Google.48 (1)", resourceCulture);
>>>>>>> main
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap z4231794819937_5cfb83c207e8528df532eae267c02d76 {
            get {
                object obj = ResourceManager.GetObject("z4231794819937_5cfb83c207e8528df532eae267c02d76", resourceCulture);
=======
        internal static System.Drawing.Bitmap Guillendesign_Variations_3_Facebook_48 {
            get {
                object obj = ResourceManager.GetObject("Guillendesign-Variations-3-Facebook.48", resourceCulture);
>>>>>>> main
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap z4231809086695_1d7a940c6208532934ca946f2a4ec942 {
            get {
                object obj = ResourceManager.GetObject("z4231809086695_1d7a940c6208532934ca946f2a4ec942", resourceCulture);
=======
        internal static System.Drawing.Bitmap Icons8_Windows_8_Security_Password_2 {
            get {
                object obj = ResourceManager.GetObject("Icons8-Windows-8-Security-Password-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_icon_150670 {
            get {
                object obj = ResourceManager.GetObject("user_icon_150670", resourceCulture);
>>>>>>> ed618cc62e6c9975de8b474ef372e0f1f3ad2b4e
>>>>>>> main
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
